### ISSUE TITLE
Handling concurrency on a production server

### ISSUE THREAD

**Issue by REEDOOX** [johnph/simple-transaction#1]
Hello, 
Thank you for this great example. I wanted to ask a question about concurrency, for what I have seen, you are using the optimistic concurrency. But on a production server, would this be suitable? Especially for an account that accepts thousands and maybe millions of transactions per day (a big store for example) a lot of transactions would still fail after retrying. 

My question to you is how would you handle concurrency on a production server ?

Thanks in advance

**EDIT** : Hello, I received your comment by email notification but I cannot see it here, I guess you deleted it. Thank you for you quick answer anyway <3 .
Playing around with the code, this version still doesn't handle if they are 2 concurrent withdrawal, you are more likely to do a dirty read on GetAccountSummary(), I wanna contribute to the project if it doesn't bother you.

As for the issue, my intent was to know if you would feel confident putting this same example on a highly solicited payment gateway. too many deposits on the same accounts would result in inconsistent data. 

Thank you again for your time!

**Comment by johnph** [comment]
Hi, 
Thanks for the comments. The concurrency handling which you see in the sample is an edge case that will occur only when multiple transaction occurs against the same record in the database which is handled through optimistic concurrency so the retry happens only in a edge case when it fails.  I think this should be sufficient because, Pessimistic concurrency is not practical in disconnected scenario's and also EF core provides no support for it.  
Regards,
John

**Comment by johnph** [comment]
Hi, Thanks for the comments. Sorry for the delayed response. Sure, No problem, you can contribute to the project and make improvements as you wish. We can push the changes. I have not tested this code in a production environment, I just wrote it for a code challenge and shared it here in github and codeproject.
